name: Build and Deploy Nginx to ACI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-javierdz-prod-francecentral
  CONTAINER_NAME: aci-javierdz-nginx-prod
  IMAGE_NAME: nginx-site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Iniciar sesión en Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Iniciar sesión en Azure Container Registry (ACR)
      - name: Docker Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 4. Construir y subir la imagen Docker etiquetada con el commit y 'latest'
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI="${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          IMAGE_LATEST="${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest"

          docker build -t $IMAGE_URI -t $IMAGE_LATEST .
          docker push $IMAGE_URI
          docker push $IMAGE_LATEST

      # 5. Desplegar / Reemplazar el contenedor en Azure Container Instances
      - name: Deploy to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.CONTAINER_NAME }} \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --registry-username ${{ secrets.REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
            --dns-name-label javierdz-dev \
            --ports 80 \
            --log-analytics-workspace ${{ secrets.WORKSPACE_ID }} \
            --log-analytics-workspace-key ${{ secrets.WORKSPACE_KEY }} \
            --restart-policy Always \
            --os-type Linux \
            --cpu 1 \
            --memory 4 \