name: Deploy Web to Azure File Share

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload files using AzCopy
        run: |
          ACCOUNT_KEY=$(az storage account keys list \
            --resource-group rg-javierdz-prod-francecentral \
            --account-name stjavierprod \
            --query "[0].value" \
            --output tsv)

          EXPIRY_DATE=$(date -u -d '30 minutes' '+%Y-%m-%dT%H:%MZ')

          SAS_TOKEN=$(az storage share generate-sas \
            --account-name stjavierprod \
            --account-key "$ACCOUNT_KEY" \
            --name nginx-site \
            --permissions rcwdl \
            --expiry "$EXPIRY_DATE" \
            --output tsv)

          azcopy copy "./*" "https://stjavierprod.file.core.windows.net/nginx-site/?$SAS_TOKEN" \
            --recursive=true \
            --exclude-path=".git;.github"

      - name: Reload Nginx Container
        run: |
          az container exec \
            --resource-group rg-javierdz-prod-francecentral \
            --name aci-javierdz-nginx-prod \
            --exec-command "nginx -s reload" || true